- 👋 Hi, I’m @Sarthak-B
- 👀 I’m interested in Python, JavaScript and PHP projects. |MUSUC PRODUCTION SKILLS INCLUDED|
- 🌱 I’m currently learning data science(AI Based).
- 💞️ I’m not looking to collaborate on anything yet.
- 📫 insta- @Sarthak_.09._ or follow on sarthakmusix.bandcamp.com to reach me.
